# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_0_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 1 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_0_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 2 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_0_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 3 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_0_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 4 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_0_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 5 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_0_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 6 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_0_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 7 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_0_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 8 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_0_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 9 -max_iteration 20

python3 AttackSetRe.py -i /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/classwise_data/class_1_seed.npy -o /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/models/resnet50_cifar10.pth -target 0 -max_iteration 20
python3 AttackSetRe.py -i /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/classwise_data/class_1_seed.npy -o /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/models/resnet50_cifar10.pth -target 2 -max_iteration 20
python3 AttackSetRe.py -i /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/classwise_data/class_1_seed.npy -o /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/models/resnet50_cifar10.pth -target 3 -max_iteration 20
python3 AttackSetRe.py -i /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/classwise_data/class_1_seed.npy -o /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/models/resnet50_cifar10.pth -target 4 -max_iteration 20
python3 AttackSetRe.py -i /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/classwise_data/class_1_seed.npy -o /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/models/resnet50_cifar10.pth -target 5 -max_iteration 20
python3 AttackSetRe.py -i /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/classwise_data/class_1_seed.npy -o /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/models/resnet50_cifar10.pth -target 6 -max_iteration 20
python3 AttackSetRe.py -i /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/classwise_data/class_1_seed.npy -o /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/models/resnet50_cifar10.pth -target 7 -max_iteration 20
python3 AttackSetRe.py -i /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/classwise_data/class_1_seed.npy -o /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 8 -max_iteration 20
python3 AttackSetRe.py -i /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/classwise_data/class_1_seed.npy -o /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/ubuntu/hbl/LargeD/ProCMG/CIFAR10/models/resnet50_cifar10.pth -target 9 -max_iteration 20

# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_2_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 0 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_2_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 1 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_2_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 3 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_2_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 4 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_2_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 5 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_2_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 6 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_2_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 7 -max_iteration 20

# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_4_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 0 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_4_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 1 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_4_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 2 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_4_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 3 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_4_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 5 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_4_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 6 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_4_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 7 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_4_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 8 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_4_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 9 -max_iteration 20

# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_5_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 0 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_5_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 1 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_5_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 2 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_5_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 3 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_5_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 4 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_5_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 6 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_5_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 7 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_5_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 8 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_5_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 9 -max_iteration 20

# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_6_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 0 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_6_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 1 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_6_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 2 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_6_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 3 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_6_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 4 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_6_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 5 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_6_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 7 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_6_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 8 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_6_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 9 -max_iteration 20

# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_7_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 0 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_7_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 1 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_7_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 2 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_7_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 3 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_7_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 4 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_7_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 5 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_7_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 6 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_7_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 8 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_7_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 9 -max_iteration 20

# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_8_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 0 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_8_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 1 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_8_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 2 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_8_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 3 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_8_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 4 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_8_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 5 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_8_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 6 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_8_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 7 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_8_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 9 -max_iteration 20

# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_9_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 0 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_9_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 1 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_9_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 2 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_9_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 3 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_9_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 4 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_9_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 5 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_9_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 6 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_9_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 7 -max_iteration 20
# python3 AttackSetRe.py -i /home/arily/LargeD/winMount/CIFAR10/classwise_data/class_9_seed.npy -o /home/arily/LargeD/winMount/CIFAR10/DistXplore/DistXplore/dist-guided/GA_output/GA_100_logits_cifar_resnet/100_50 -pop_num 100 -subtotal 50 -type mnist -model /home/arily/LargeD/winMount/CIFAR10/models/resnet50_cifar10.pth -target 8 -max_iteration 20
